LOCAL_NUCLEUS_ASSET_ROOT_DIR = "data/NUCLEUS"
LOCAL_ISAAC_NUCLEUS_DIR = f"{LOCAL_NUCLEUS_ASSET_ROOT_DIR}/Isaac"
LOCAL_NVIDIA_NUCLEUS_DIR = f"{LOCAL_NUCLEUS_ASSET_ROOT_DIR}/NVIDIA"

from .a1arm import A1ARM_CFG, A1ARM_RGM3_CFG
from .cabinet import CABINET_CFG